name: GitHub Actions Build and Deploy

# 触发条件: push 到 master 分支后
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # 只在下列路径变更时触发
    paths:
      - 'docs/**'
      - 'package.json'

# 设置上海时区
env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 设置 Node 版本
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          # 可选：配置缓存以加快构建速度
          cache: 'npm'

      # 安装依赖
      - name: Install Dependencies
        run: npm install

      # 打包静态文件
      - name: Build
        run: npm run build

      - name: Copy files
        run: cp README.md ./dist/

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # GitHub 密钥
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 指定仓库
          REPOSITORY_NAME: 807660937/upoe.top
          # GitHub Pages 读取的分支
          BRANCH: gh-pages
          # 静态文件所在目录
          FOLDER: dist
